steps:
  # Step 1: Checkout the code from GitHub
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/Misbahhassan08/guage_control']
  
  # Step 2: Change directory to the repository
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'guagecontrol'
    args: ['build', '-t', 'gcr.io/myprojectems-435411/guagecontrol', '.']

  
  # Step 3: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'guagecontrol'
    args: ['push', 'gcr.io/myprojectems-435411/guagecontrol']
  
  # Step 4: Deploy the Docker image to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'guagecontrol'
      - '--image'
      - 'gcr.io/myprojectems-435411/guagecontrol'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--quiet'
      

timeout: '1200s'  # Adjust timeout as necessary
options:
  logging: CLOUD_LOGGING_ONLY
